spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=UTC
    username: root
    password: 123456
server:
  servlet:
    context-path: /sell